services:
  # Qdrant vector database for OpenMemory (following original naming)
  mem0_store:
    image: qdrant/qdrant
    ports:
      - "6335:6333"  # Different port to avoid conflict with main Qdrant
    volumes:
      - ./data/mem0_storage:/qdrant/storage
    restart: unless-stopped

  # OpenMemory MCP Server (built from local cache)
  openmemory-mcp:
    build:
      context: ./cache/mem0/openmemory/api
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENMEMORY_USER_ID=${OPENMEMORY_USER_ID:-openmemory}
    depends_on:
      - mem0_store
    ports:
      - "8765:8765"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; exit(0 if requests.get('http://localhost:8765/docs').status_code == 200 else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # OpenMemory UI (optional - can be disabled if not needed)
  openmemory-ui:
    image: mem0/openmemory-ui:latest
    ports:
      - "3001:3000"  # Different port to avoid conflict
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8765
      - NEXT_PUBLIC_USER_ID=openmemory
    depends_on:
      - openmemory-mcp
    profiles:
      - ui  # Only starts when --profile ui is used