apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: friend-lite
build:
  tagPolicy:
    dateTime:
      format: "2006-01-02_15-04-05"
      timezone: "UTC"
profiles:
  - name: moonshine-asr
    build:
      artifacts:
        - image: moonshine-asr
          context: extras/asr-services
          docker:
            dockerfile: Dockerfile_Moonshine
    deploy:
      helm:
        releases:
          - name: moonshine-asr
            chartPath: extras/asr-services/charts/moonshine
            namespace: speech
            createNamespace: true
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO_moonshine_asr}}"
              image.tag: "{{.IMAGE_TAG_moonshine_asr}}"

  - name: parakeet-asr
    build:
      artifacts:
        - image: parakeet-asr
          context: extras/asr-services
          docker:
            dockerfile: Dockerfile_Parakeet
    deploy:
      helm:
        releases:
          - name: parakeet-asr
            chartPath: extras/asr-services/charts/parakeet
            namespace: speech
            createNamespace: true
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO_parakeet_asr}}"
              image.tag: "{{.IMAGE_TAG_parakeet_asr}}"

  - name: speaker-recognition
    build:
      local:
        push: true
        useDockerCLI: true
      artifacts:
        - image: speaker-recognition
          context: extras/speaker-recognition
          docker:
            dockerfile: Dockerfile-k8s
            buildArgs:
              COMPUTE_MODE: "{{.COMPUTE_MODE}}"
        - image: speaker-recognition-ui
          context: extras/speaker-recognition/webui
          docker:
            dockerfile: Dockerfile
            buildArgs:
              VITE_ALLOWED_HOSTS: "{{.VITE_ALLOWED_HOSTS}}"
    deploy:
      helm:
        releases:
          - name: speaker-recognition
            chartPath: extras/speaker-recognition/charts
            namespace: speech
            setValueTemplates:
              speaker.image.repository: "{{.IMAGE_REPO_speaker_recognition}}"
              speaker.image.tag: "{{.IMAGE_TAG_speaker_recognition}}"
              webui.image.repository: "{{.IMAGE_REPO_speaker_recognition_ui}}"
              webui.image.tag: "{{.IMAGE_TAG_speaker_recognition_ui}}"
              secrets.hfToken: "{{.HF_TOKEN}}"
              secrets.deepgramApiKey: "{{.DEEPGRAM_API_KEY}}"
              speaker.env.SIMILARITY_THRESHOLD: "{{.SIMILARITY_THRESHOLD}}"
              speaker.env.COMPUTE_MODE: "{{.COMPUTE_MODE}}"
              speaker.env.SPEAKER_SERVICE_HOST: "{{.SPEAKER_SERVICE_HOST}}"
              speaker.env.SPEAKER_SERVICE_PORT: "{{.SPEAKER_SERVICE_PORT}}"
              webui.env.REACT_UI_HOST: "{{.REACT_UI_HOST}}"
              webui.env.REACT_UI_PORT: "{{.REACT_UI_PORT}}"
              webui.env.REACT_UI_HTTPS: "{{.REACT_UI_HTTPS}}"
              webui.env.WEBUI_CORS_ORIGIN: "{{.WEBUI_CORS_ORIGIN}}"
              webui.env.VITE_ALLOWED_HOSTS: "{{.VITE_ALLOWED_HOSTS}}"
              ingress.host: "{{.SPEAKER_HOST}}"
              env.BACKEND_HOST: "{{.BACKEND_HOST}}"
              # Shared models configuration
              global.sharedModels.enabled: "true"
              global.sharedModels.useHostPath: "true"
              global.sharedModels.size: "20Gi"
              global.sharedModels.hostPath: "/shared/models"

  # Infrastructure profile - deploy once, rarely updated
  - name: infrastructure
    deploy:
      helm:
        releases:
          # Infrastructure components using Bitnami charts
          - name: mongodb
            remoteChart: oci://registry-1.docker.io/bitnamicharts/mongodb
            version: "16.5.1"
            namespace: "{{.INFRASTRUCTURE_NAMESPACE}}"
            createNamespace: true
            setValueTemplates:
              auth.enabled: "false"
              persistence.size: "10Gi"
              persistence.storageClass: "openebs-hostpath"
              service.nameOverride: "mongodb"
              
          - name: qdrant
            chartPath: backends/charts/qdrant
            namespace: "{{.INFRASTRUCTURE_NAMESPACE}}"
            setValueTemplates:
              persistence.size: "10Gi"
              persistence.storageClass: "openebs-hostpath"

  # Application profile - frequently updated
  - name: advanced-backend
    build:
      local:
        push: true
        useDockerCLI: true
      artifacts:
        - image: advanced-backend
          context: backends/advanced
          docker:
            dockerfile: Dockerfile.k8s
        - image: webui
          context: backends/advanced/webui
          docker:
            dockerfile: Dockerfile
            buildArgs:
              VITE_BACKEND_URL: ""
              VITE_ALLOWED_HOSTS: "{{.VITE_ALLOWED_HOSTS}}"

    deploy:
      helm:
        releases:
          # Application components using custom charts
          - name: advanced-backend
            chartPath: backends/charts/advanced-backend
            namespace: "{{.APPLICATION_NAMESPACE}}"
            createNamespace: true
            valuesFiles:
              - backends/charts/advanced-backend/ingress-values.yaml
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO_advanced_backend}}"
              image.tag: "{{.IMAGE_TAG_advanced_backend}}"
              # Override specific Kubernetes-specific values
              env.MONGODB_URI: "mongodb://mongodb.{{.INFRASTRUCTURE_NAMESPACE}}.svc.cluster.local:27017/friend"
              env.QDRANT_BASE_URL: "qdrant.{{.INFRASTRUCTURE_NAMESPACE}}.svc.cluster.local"
              # Auto-generated environment variables from skaffold.env
              env.BACKEND_HOST: "{{.BACKEND_HOST}}"
              env.WEBUI_HOST: "{{.WEBUI_HOST}}"
              env.SPEAKER_HOST: "{{.SPEAKER_HOST}}"
              env.HF_TOKEN: "{{.HF_TOKEN}}"
              env.DEEPGRAM_API_KEY: "{{.DEEPGRAM_API_KEY}}"
              env.SIMILARITY_THRESHOLD: "{{.SIMILARITY_THRESHOLD}}"
              env.SPEAKER_SERVICE_HOST: "{{.SPEAKER_SERVICE_HOST}}"
              env.SPEAKER_SERVICE_PORT: "{{.SPEAKER_SERVICE_PORT}}"
              env.SPEAKER_SERVICE_URL: "{{.SPEAKER_SERVICE_URL}}"
              env.REACT_UI_HOST: "{{.REACT_UI_HOST}}"
              env.REACT_UI_PORT: "{{.REACT_UI_PORT}}"
              env.WEBUI_CORS_ORIGIN: "{{.WEBUI_CORS_ORIGIN}}"
              env.MEMORY_PROVIDER: "{{.MEMORY_PROVIDER}}"
              env.OPENMEMORY_MCP_URL: "{{.OPENMEMORY_MCP_URL}}"
              persistence.storageClass: "openebs-hostpath"
              persistence.size: "10Gi"
              service.nodePort: "{{.BACKEND_NODEPORT}}"
              # Ingress configuration - Using escaped values to handle domains with dots
              ingress.hosts[0].host: "{{.BACKEND_HOST}}"
              ingress.hosts[1].host: "{{.EXTERNAL_DOMAIN}}"
              # CORS_ORIGINS - Temporarily disabled due to Helm parsing issues with domains containing dots and commas
              # env.CORS_ORIGINS: "https://{{.BACKEND_HOST}},http://{{.BACKEND_HOST}},https://{{.EXTERNAL_DOMAIN}},http://{{.EXTERNAL_DOMAIN}}"


          - name: webui
            chartPath: backends/charts/webui
            namespace: "{{.APPLICATION_NAMESPACE}}"
            valuesFiles:
              - backends/charts/webui/ingress-values.yaml
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO_webui}}"
              image.tag: "{{.IMAGE_TAG_webui}}"
              # Auto-generated environment variables from skaffold.env
              env.WEBUI_HOST: "{{.WEBUI_HOST}}"
              env.BACKEND_HOST: "{{.BACKEND_HOST}}"
              env.SPEAKER_HOST: "{{.SPEAKER_HOST}}"
              env.WEBUI_CORS_ORIGIN: "{{.WEBUI_CORS_ORIGIN}}"
              env.REACT_UI_HOST: "{{.REACT_UI_HOST}}"
              env.REACT_UI_PORT: "{{.REACT_UI_PORT}}"
              service.nodePort: "{{.WEBUI_NODEPORT}}"
              # Ingress configuration handled via values file due to Helm --set parsing limitations
              # See: generated-values.yaml files created by Makefile
              # VITE_ALLOWED_HOSTS moved to build-time configuration

  - name: speaker-recognition-gtx1070
    build:
      local:
        push: true
        useDockerCLI: true
      artifacts:
        - image: speaker-recognition
          context: extras/speaker-recognition
          docker:
            dockerfile: Dockerfile-gtx1070
        - image: speaker-recognition-ui
          context: extras/speaker-recognition/webui
          docker:
            dockerfile: Dockerfile
            buildArgs:
              VITE_ALLOWED_HOSTS: "{{.VITE_ALLOWED_HOSTS}}"
    deploy:
      helm:
        releases:
          - name: speaker-recognition
            chartPath: extras/speaker-recognition/charts
            namespace: speech
            setValueTemplates:
              speaker.image.repository: "{{.IMAGE_REPO_speaker_recognition}}"
              speaker.image.tag: "{{.IMAGE_TAG_speaker_recognition}}"
              webui.image.repository: "{{.IMAGE_REPO_speaker_recognition_ui}}"
              webui.image.tag: "{{.IMAGE_TAG_speaker_recognition_ui}}"
              secrets.hfToken: "{{.HF_TOKEN}}"
              secrets.deepgramApiKey: "{{.DEEPGRAM_API_KEY}}"
              speaker.env.SIMILARITY_THRESHOLD: "{{.SIMILARITY_THRESHOLD}}"
              speaker.env.COMPUTE_MODE: "{{.COMPUTE_MODE}}"
              speaker.env.SPEAKER_SERVICE_HOST: "{{.SPEAKER_SERVICE_HOST}}"
              speaker.env.SPEAKER_SERVICE_PORT: "{{.SPEAKER_SERVICE_PORT}}"
              webui.env.REACT_UI_HOST: "{{.REACT_UI_HOST}}"
              webui.env.REACT_UI_PORT: "{{.REACT_UI_PORT}}"
              webui.env.REACT_UI_HTTPS: "{{.REACT_UI_HTTPS}}"
              # webui environment variables set by main speaker-recognition profile to avoid duplicates
              # webui.env.WEBUI_CORS_ORIGIN: "{{.WEBUI_CORS_ORIGIN}}"
              # webui.env.VITE_ALLOWED_HOSTS: "{{.VITE_ALLOWED_HOSTS}}"
              ingress.host: "{{.SPEAKER_HOST}}"
              # Shared models configuration
              global.sharedModels.enabled: "true"
              global.sharedModels.useHostPath: "true"
              global.sharedModels.size: "20Gi"
              global.sharedModels.hostPath: "/shared/models"


