apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: friend-lite
build:
  tagPolicy:
    dateTime:
      format: "2006-01-02_15-04-05"
      timezone: "UTC"
profiles:
  - name: moonshine-asr
    build:
      artifacts:
        - image: moonshine-asr
          context: extras/asr-services
          docker:
            dockerfile: Dockerfile_Moonshine
    deploy:
      helm:
        releases:
          - name: moonshine-asr
            chartPath: extras/asr-services/charts/moonshine
            namespace: speech
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO_moonshine_asr}}"
              image.tag: "{{.IMAGE_TAG_moonshine_asr}}"

  - name: speaker-recognition
    build:
      local:
        push: true
        useDockerCLI: true
      artifacts:
        - image: speaker-recognition
          context: extras/speaker-recognition
          docker:
            dockerfile: Dockerfile
            buildArgs:
              COMPUTE_MODE: "{{.COMPUTE_MODE}}"
        - image: speaker-recognition-ui
          context: extras/speaker-recognition/webui
          docker:
            dockerfile: Dockerfile
    deploy:
      helm:
        releases:
          - name: speaker-recognition
            chartPath: extras/speaker-recognition/charts
            namespace: speech
            setValueTemplates:
              speaker.image.repository: "{{.IMAGE_REPO_speaker_recognition}}"
              speaker.image.tag: "{{.IMAGE_TAG_speaker_recognition}}"
              webui.image.repository: "{{.IMAGE_REPO_speaker_recognition_ui}}"
              webui.image.tag: "{{.IMAGE_TAG_speaker_recognition_ui}}"
              secrets.hfToken: "{{.HF_TOKEN}}"
              secrets.deepgramApiKey: "{{.DEEPGRAM_API_KEY}}"
              speaker.env.SIMILARITY_THRESHOLD: "{{.SIMILARITY_THRESHOLD}}"
              speaker.env.COMPUTE_MODE: "{{.COMPUTE_MODE}}"
              speaker.env.SPEAKER_SERVICE_HOST: "{{.SPEAKER_SERVICE_HOST}}"
              speaker.env.SPEAKER_SERVICE_PORT: "{{.SPEAKER_SERVICE_PORT}}"
              webui.env.REACT_UI_HOST: "{{.REACT_UI_HOST}}"
              webui.env.REACT_UI_PORT: "{{.REACT_UI_PORT}}"
              webui.env.REACT_UI_HTTPS: "{{.REACT_UI_HTTPS}}"
              ingress.hosts[0].host: "{{.INGRESS_HOST}}"

  # Infrastructure profile - deploy once, rarely updated
  - name: infrastructure
    deploy:
      helm:
        releases:
          # Infrastructure components using Bitnami charts
          - name: mongodb
            remoteChart: oci://registry-1.docker.io/bitnamicharts/mongodb
            version: "16.5.1"
            namespace: "{{.INFRASTRUCTURE_NAMESPACE}}"
            createNamespace: true
            setValueTemplates:
              auth.enabled: "false"
              persistence.size: "10Gi"
              persistence.storageClass: "openebs-hostpath"
              service.nameOverride: "mongodb"
              
          - name: qdrant
            chartPath: backends/charts/qdrant
            namespace: "{{.INFRASTRUCTURE_NAMESPACE}}"
            setValueTemplates:
              persistence.size: "10Gi"
              persistence.storageClass: "openebs-hostpath"

  # Application profile - frequently updated
  - name: advanced-backend
    build:
      local:
        push: true
        useDockerCLI: true
      artifacts:
        - image: advanced-backend
          context: backends/advanced
          docker:
            dockerfile: Dockerfile.k8s
        - image: webui
          context: backends/advanced/webui
          docker:
            dockerfile: Dockerfile
            buildArgs:
              VITE_BACKEND_URL: ""

    deploy:
      helm:
        releases:
          # Application components using custom charts
          - name: advanced-backend
            chartPath: backends/charts/advanced-backend
            namespace: "{{.APPLICATION_NAMESPACE}}"
            createNamespace: true
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO_advanced_backend}}"
              image.tag: "{{.IMAGE_TAG_advanced_backend}}"
              # Override specific Kubernetes-specific values
              env.MONGODB_URI: "mongodb://mongodb.{{.INFRASTRUCTURE_NAMESPACE}}.svc.cluster.local:27017/friend"
              env.QDRANT_BASE_URL: "qdrant.{{.INFRASTRUCTURE_NAMESPACE}}.svc.cluster.local"
              env.CORS_ORIGINS: "http://localhost:3010\\,http://localhost:3001\\,http://127.0.0.1:3010\\,http://{{.BACKEND_IP}}:{{.WEBUI_NODEPORT}}\\,https://friend-lite.192-168-1-42.nip.io"
              persistence.storageClass: "openebs-hostpath"
              persistence.size: "10Gi"
              service.nodePort: "{{.BACKEND_NODEPORT}}"
            setValues:
              image.repository: "advanced-backend"
              
          - name: webui
            chartPath: backends/charts/webui
            namespace: "{{.APPLICATION_NAMESPACE}}"
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO_webui}}"
              image.tag: "{{.IMAGE_TAG_webui}}"
              service.nodePort: "{{.WEBUI_NODEPORT}}"
            setValues:
              image.repository: "webui"

