services:
  parakeet-ws:
    build: .
    image: parakeet-ws:latest
    ports:
      - "8080:8080"
    volumes:
      # Persist Hugging Face cache (models + tokenizer) between restarts
      - ./model_cache:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - HF_HOME=/models
    restart: unless-stopped
    