# Default values for qdrant
replicaCount: 1

image:
  repository: qdrant/qdrant
  pullPolicy: IfNotPresent
  tag: "v1.15.4"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 6333
  grpcPort: 6334

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

persistence:
  enabled: true
  storageClass: "openebs-hostpath"
  accessMode: ReadWriteOnce
  size: 10Gi
  mountPath: /qdrant/storage

# Pod-level security context
podSecurityContext:
  fsGroup: 1000

# Container-level security context
containerSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true

nodeSelector: {}
tolerations: []
affinity: {}
