# Default values for speaker-recognition chart

speaker:
  image:
    repository: speaker-recognition
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8085
  resources:
    requests:
      memory: "2Gi"
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "2000m"
  nvidia:
    enabled: true
  persistence:
    modelCache:
      enabled: true
      size: 10Gi
    audioChunks:
      enabled: true
      size: 1Gi
    debug:
      enabled: true
      size: 1Gi
    speakerData:
      enabled: true
      size: 1Gi
  env:
    SIMILARITY_THRESHOLD: "0.15"
    SPEAKER_SERVICE_HOST: "0.0.0.0"
    SPEAKER_SERVICE_PORT: "8085"

webui:
  image:
    repository: speaker-recognition-ui
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5173
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  env:
    REACT_UI_HOST: "0.0.0.0"
    REACT_UI_PORT: "5173"
    REACT_UI_HTTPS: "false"

# Global shared configuration
global:
  sharedModels:
    enabled: true
    size: 20Gi
    # Use the working openebs-hostpath storage class
    storageClassName: "openebs-hostpath"
    
    # Disable HostPath since we're using external PVC
    useHostPath: false
    
    # Use external PVC created in k8s-manifests
    useExternalPVC: true
    
    # Pre-download models using init job
    initJob:
      enabled: false

# Secrets configuration
secrets:
  # Set these values when deploying:
  # --set secrets.hfToken="your_hf_token_here"
  # --set secrets.deepgramApiKey="your_deepgram_key_here"
  hfToken: ""
  deepgramApiKey: ""