apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: parakeet
  name: parakeet
spec:
  ports:
    - name: http
      port: 8765
      targetPort: 8765
  selector:
    io.kompose.service: parakeet
