# Default values for moonshine-asr
image:
  repository: moonshine-asr
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8765

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector:
  nvidia.com/gpu.present: "true"

tolerations:
  - key: "gpu"
    operator: "Equal"
    value: "only"
    effect: "NoSchedule"

affinity: {}

persistence:
  enabled: true
  size: 10Gi
  storageClass: ""
  accessMode: ReadWriteOnce
