{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "advanced-backend.fullname" . }}-data
  labels:
    {{- include "advanced-backend.labels" . | nindent 4 }}
  annotations:
    openebs.io/hostpath: "/var/openebs/{{ include "advanced-backend.fullname" . }}-data"
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
{{- end }}

