[project]
name = "speaker-recognition-service"
version = "0.1.0"
description = "Speaker recognition and diarization service for friend-lite"
requires-python = ">=3.10"

dependencies = [
    "fastapi>=0.115.12",
    "uvicorn>=0.34.2",
    "numpy>=1.26",
    "scipy>=1.10.0",
    "torch>=2.7.0",
    "torchaudio>=2.7.0",
    "pyannote.audio>=3.3.2",
    "faiss-cpu>=1.7.1",
    "aiohttp>=3.8.0",
    "python-multipart>=0.0.6",
    "pydantic>=2.0.0",
    "soundfile>=0.12",
    "easy-audio-interfaces[local-audio]>=0.7.1",
    "pydantic-settings>=2.10.1",
    "deepgram-sdk>=4.7.0",
    "pydub>=0.25.1",
    "yt-dlp>=2025.7.21",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "isort>=6.0.1",
]
gpu = [
    "faiss-gpu>=1.7.1",
]

[tool.isort]
profile = "black" 


[tool.uv]
compile-bytecode = false

[tool.uv.sources]
torchaudio  = { index = "pytorch-cu128",   marker = "sys_platform != 'darwin'" }
torchvision  = { index = "pytorch-cu128",   marker = "sys_platform != 'darwin'" }
torch = [
  { index  = "pytorch-cu128", marker = "sys_platform != 'darwin'" },
]

[[tool.uv.index]]
name = "pypi"
url  = "https://pypi.org/simple"

[[tool.uv.index]]
name = "pytorch-cu128"
url  = "https://download.pytorch.org/whl/cu128"
