# syntax=docker/dockerfile:1

#########################  builder #################################
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim AS builder

# Accept CUDA version as build argument
ARG CUDA_VERSION

WORKDIR /app

# NeMo and texterrors need libs and C++ compiler
RUN apt-get update && apt-get install -y --no-install-recommends \
        libsndfile1 \
        build-essential git portaudio19-dev \
    && rm -rf /var/lib/apt/lists/*

# Dependency manifest first for cache‑friendly installs
COPY pyproject.toml uv.lock ./
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --no-install-project --group parakeet --extra ${CUDA_VERSION}

# Should prepare the .venv for use :)

#########################  runtime #################################
FROM python:3.12-slim-bookworm AS runtime
ENV PYTHONUNBUFFERED=1
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends libsndfile1 build-essential portaudio19-dev curl && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app /app
COPY . .
ENV PATH="/app/.venv/bin:$PATH"

EXPOSE 8765

CMD ["python", "parakeet-offline.py", "--port", "8765"]